#    https://github.com/asciidoctor/asciidoctor-pdf/blob/main/data/themes/default-theme.yml
extends: default
#base:
#    font-color: #FF0000
role:
    green:
        background_color: #00FF00
    test:
        background_color: #00FF00
    question:
        background_color: #FFE932
    keyword:
        font-color: #E25800

heading:
    font_color: #E25800