ifndef::_main_loaded[]
include::../config/load_attributes.adoc[]
endif::_main_loaded[]
//titre de la section
[[implémentation_d_une_association_bidirectionnelle_multiple]]
= Implémentation d'une association bidirectionnelle multiple
ifndef::_main_loaded[]
include::../config/header_attributes.adoc[]
{empty}
Point précédent :
link:implementation-d-une-association-bidirectionnelle-simple.adoc[Implémentation d'une association bidirectionnelle simple]
endif::_main_loaded[]

[NOTE]
====
*Rappel 1* : une association entre deux classes `A` et `B` traduit un lien de contenance.
Dans ce cas `A` doit prévoir un attribut permettant de stocker une instance de  `B` et/ou vice-versa.


*Rappel 2* : une association bidirectionnelle est navigable dans les deux sens (de `A` vers `B` *ET* de `B` vers `A`).

*Rappel 3* : Une association est qualifiée de multiple lorsque zéro, une ou plusieurs instances de `B` sont liées à `A` (ou l'inverse).

*Rappel 4* : Dans une association bidirectionnelle, il faut choisir la classe propriétaire qui va être responsable de la mise à jour de l'objet inverse.
====

Le diagramme suivant exprime une association bidirectionnelle multiple car au moins une des cardinalités maximales de l'association est à plusieurs.

ifeval::[{_show_plantuml} == 1]
[plantuml,target=asso_bi_multiple,format=svg]
....
hide circle
skinparam classAttributeIconSize 0

class Vehicle {
- registerNumber: string
+__toString():string
}

class Technician {
-name: string
+__toString():string
}
left to right direction
Vehicle "0..1" -- "*" Technician : maintains
....
// end _show_plantuml
endif::[]


Lecture de l'association : Un véhicule est maintenu par 0, 1 ou plusieurs techniciens et un technicien maintient 0 ou un véhicule.

Nous avons appris dans le cadre de l'<<implémentation_d_une_association_bidirectionnelle_simple,implémentation d'une association bidirectionnelle simple>> qu'il fallait choisir la <<keyword_classe_propriétaire,classe propriétaire>>.

Compte tenu de notre diagramme, la classe propriétaire sera `Technician` car c'est celle qui est à l’opposée de la cardinalité maximale à 1.

A ce niveau, il n'y a plus rien de nouveau pour nous.
L'implémentation se fera en plusieurs étapes :

. Mettre en place la navigabilitié de `Vehicule` vers `Technician` (en utilisant un attribut permettant de contenir une <<keyword_collection,collection>>)
. Mettre en place la navigabilitié de `Technician` vers `Vehicule` (en utilisant un attribut permettant de contenir zéro ou une instance de `Vehicle`)
. Mettre en place dans la classe propriétaire `Technician` la mise à jour de l'objet inverse.

[.question]
****
*Q{counter:_question})*
Travail à faire

* Implémentez scrupuleusement le diagramme suivant (les propriétés `registerNumber` et `name` seront toutes les deux initialisées dans les constructeurs. Inutile de prévoir des mutateur et accesseur les concernant) :

ifeval::[{_show_plantuml} == 1]
[plantuml,target=asso_bi_multiple_1,format=svg]
....
hide circle
skinparam classAttributeIconSize 0

class Vehicle {
-registerNumber
}

class Technician {
-name
}

left to right direction
Vehicle "0..1" -- "*" Technician : maintains
....
// end _show_plantuml
endif::[]

* Testez votre implémentation en répondant aux questions suivantes :

[loweralpha, start=1]
. Créez deux instances de véhicules respectivement référencées par les variables `$vA` et `$vB`.
Faire un `var_dump()` de chaque variable et noter l'identifiant propre à chaque objet (un identifiant est un `#` suivi d'un chiffre tel que `#1`)
. Créez trois instances de technicien respectivement référencées par les variables `$paul`, `$juliette` et `$jalila` (leur affecter le prénom correspondant aux noms des variables).
Faire un `var_dump()` de chaque technicien et noter l'identifiant d'objet qui leur est propre.
. Associez le véhicule A aux techniciens Paul et Juliette et le véhicule B au technicien Jalila (il ne faut pas oublier que l'objet responsable de la mise à jour de l'objet lié est la technicien).
Faire un var_dump de chaque véhicule afin de constater que la mise à jour de l'objet inverse (ici Vehicle) a été réalisée à partir de la classe Technician. Noter pour chaque voiture le ou les techniciens associés.
. Associez le véhicule B au technicien Paul (sans oublier qui est la classe propriétaire).
Constatez que le fait d'avoir affecté le véhicule B à Paul à produit trois effets :
- Paul n'est plus associé au véhicule A
- Le véhicule A n'est plus associé au technicien Paul mais encore à Juliette.
- Le véhicule B est associé au technicien Paul
//end _question
****

ifeval::[{_show_correction} == 1]
[.answer]
****
_Correction de Q{_question}_

* Nous sommes dans le cas d'une navigabilité bidirectionnelle.
Il faut choisir la classe propriétaire.
Ce sera la classe `Technician` car elle est associée à `Vehicle` avec une cardinalité maximale à 1 alors que le lien dans l'autre sens est multiple.

* Voici le code de la classe `Vehicule` (navigable vers `Technician` avec son attribut `technicians` permettant de stocker une collection d'objets `Technician`).

_Cette correction reprend tous les concepts que nous avons abordés dans les parties précédentes._

[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;class_Vehicle]
----
* Classe `Technician` (navigable vers `Vehicule`)

[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;class_Technician;method_setVehicle]
----

* Mise à jour depuis la classe propriétaire `Technician` de l'objet inverse de type `Vehicle`.

[source%linenums,php]
----
//class Technician
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;method_setVehicle;maj_inverse_vehicle]
----


* Réponse à la *question a* (création de 2 véhicules et récupération de leur identifiant php)
+
[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;question_a]
----
+
[source%linenums,text, subs="attributes"]
----
-----------------------
*** var_dump de $vA :
-----------------------
object(Vehicle)#1 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "AAAA"
  ["technicians":"Vehicle":private]=>
  array(0) {
  }
}
L'identifiant de $vA est #1. Le véhicule A n'est associé à aucun technicien.
-----------------------
*** var_dump de $vB :
-----------------------
object(Vehicle)#2 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "BBBB"
  ["technicians":"Vehicle":private]=>
  array(0) {
  }
}
L'identifiant de $vB est #2. Le véhicule B n'est associé à aucun technicien.
----

* Réponses à la *question b* (création de 3 techniciens et récupération de leur identifiant php)
+
[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;question_b]
----
+
[source,text]
----
-----------------------
*** var_dump de $paul :
-----------------------
object(Technician)#3 (2) {
  ["name":"Technician":private]=>
  string(4) "Paul"
  ["vehicle":"Technician":private]=>
  NULL
}
L'identifiant de $paul est #3. Paul n'est associé à aucune voiture.-----------------------
*** var_dump de $juliette :
-----------------------
object(Technician)#4 (2) {
  ["name":"Technician":private]=>
  string(8) "Juliette"
  ["vehicle":"Technician":private]=>
  NULL
}
L'identifiant de $juliette est #4. Juliette n'est associée à aucune voiture.-----------------------
*** var_dump de $jalila :
-----------------------
object(Technician)#5 (2) {
  ["name":"Technician":private]=>
  string(6) "Jalila"
  ["vehicle":"Technician":private]=>
  NULL
}
L'identifiant de $jalila est #5. Jalila n'est associée à aucune voiture.
----

* Réponses à la *question c* (association du véhicule A à Paul et Juliette et B à Jalila et vérifier que A et B ont bien leurs techniciens)
+
[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;question_c]
----
+
[source,text]
----
-----------------------
*** var_dump de $vA :
-----------------------
object(Vehicle)#1 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "AAAA"
  ["technicians":"Vehicle":private]=>
  array(2) {
    [0]=>
    object(Technician)#3 (2) {
      ["name":"Technician":private]=>
      string(4) "Paul"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
    [1]=>
    object(Technician)#4 (2) {
      ["name":"Technician":private]=>
      string(8) "Juliette"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
  }
}
Le véhicule A (#1) est associé aux techniciens Paul et Juliette.
-----------------------
*** var_dump de $vB :
-----------------------
object(Vehicle)#2 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "BBBB"
  ["technicians":"Vehicle":private]=>
  array(1) {
    [0]=>
    object(Technician)#5 (2) {
      ["name":"Technician":private]=>
      string(6) "Jalila"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
  }
}
Le véhicule B (#2) est associé au technicien Jalila.
----

* Réponses à la *question d* (association du véhicule B à Paul (qui était jusque là associé au véhicule A) et contrôle des effets)
+
[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_zeroone_to_multiple_tehnicians_bi.php[tags=!*;question_d]
----
+
[source,text]
----
-----------------------
*** var_dump de $paul :
-----------------------
object(Technician)#3 (2) {
  ["name":"Technician":private]=>
  string(4) "Paul"
  ["vehicle":"Technician":private]=>
  object(Vehicle)#2 (2) {
    ["registerNumber":"Vehicle":private]=>
    string(4) "BBBB"
    ["technicians":"Vehicle":private]=>
    array(2) {
      [0]=>
      object(Technician)#5 (2) {
        ["name":"Technician":private]=>
        string(6) "Jalila"
        ["vehicle":"Technician":private]=>
        *RECURSION*
      }
      [1]=>
      *RECURSION*
    }
  }
}
L'identifiant de $paul est #3. Paul n'est associé à aucune voiture.
-----------------------
*** var_dump de $vA :
-----------------------
object(Vehicle)#1 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "AAAA"
  ["technicians":"Vehicle":private]=>
  array(1) {
    [1]=>
    object(Technician)#4 (2) {
      ["name":"Technician":private]=>
      string(8) "Juliette"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
  }
}
Le véhicule A (#1) est encore associé à Juliette.
-----------------------
*** var_dump de $vB :
-----------------------
object(Vehicle)#2 (2) {
  ["registerNumber":"Vehicle":private]=>
  string(4) "BBBB"
  ["technicians":"Vehicle":private]=>
  array(2) {
    [0]=>
    object(Technician)#5 (2) {
      ["name":"Technician":private]=>
      string(6) "Jalila"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
    [1]=>
    object(Technician)#3 (2) {
      ["name":"Technician":private]=>
      string(4) "Paul"
      ["vehicle":"Technician":private]=>
      *RECURSION*
    }
  }
}
Le véhicule B (#2) est maintenant associé à Paul en plus de Jalila.
----
****
//end _show_correction
endif::[]

ifndef::_hide_breakpoint[]
//todo: breakpoint à supprimer
:breakpoint_date: mar. 04/04 à 14:17
//on masque la correction à partir de ce point
:_show_correction: 0
#Point d'arrêt du cours au mar. 04/04 à 14:17#
endif::_hide_breakpoint[]

[.question]
****
*Q{counter:_question})*
Travail à faire

* Implémentez scrupuleusement le diagramme ci-dessous (les propriétés `registerNumber` et `name` seront toutes les deux initialisées dans les constructeurs. Inutile de prévoir des mutateur et accesseur les concernant). (testez votre implémentation en ajoutant / retirant des techniciens aux voitures et en consultant le contenu des objets avec des `var_dump()`)

ifeval::[{_show_plantuml} == 1]
[plantuml,target=asso_bi_multiple_2,format=svg]
....
hide circle
skinparam classAttributeIconSize 0

class Vehicle{
-registerNumber
}

class Technician {
-name
}

left to right direction
Vehicle "*" -- "*" Technician : maintains
....
// end _show_plantuml

[NOTE]
====
Nous partirons du principe que la classe propriétaire est `Technician` afin que la correction corresponde à votre travail.
====

//end _question
****

ifeval::[{_show_correction} == 1]
[.answer]
****
_Correction de Q{_question}_

Nous sommes dans le cas d'une association bidirectionnelle.
Il faut déterminer la classe propriétaire.

Ici les cardinalités maximales sont multiples des deux côtés de l'association.
Il faut donc choisir la classe qu'il est le plus naturel d'utiliser, c'est-à-dire la classe dominante.

Si vous considérez qu'il est plus naturel d'affecter un technicien à une voiture, alors la classe dominante sera `Vehicle`.

Si vous considérez qu'il est plus naturel d'affecter une voiture à un technicien, alors la classe dominante sera `Technician`.

Si je me place du point de vue d'un garage, il peut paraître plus naturel d'affecter un véhicule à un technicien.
Il est plus logique de dire que Paul doit s'occuper de la voiture A que de dire que la voiture A va être réparée par Paul (enfin, selon moi).
Dans ce cas, la classe dominante est la classe `Technician`.

La correction proposée affecte la responsabilité de la mise à jour de l'objet inverse à la classe `Technician`.

* Voici le code de la classe `Vehicle` qui doit être navigable vers les techniciens liés à elle.
Puisqu'il y en a plusieurs, une collection est utilisée pour les stocker.

[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_multiple_to_multiple_technician_bi.php[tags=!*;class_Vehicle;]
----

* Voici le code de la classe `Technician` qui doit être navigable vers les véhicules liés à elle.
Puisqu'il y en a plusieurs, une collection est utilisée pour les stocker.

[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_multiple_to_multiple_technician_bi.php[tags=!*;class_Technician;mutator_accessor_of_vehicle]
----

* Il ne reste plus qu'à prévoir la mise à jour de l'objet inverse depuis la classe dominante (ici `Technician`)

[source%linenums,php]
----
include::../assets/source_code/_implementation_vehicle_multiple_to_multiple_technician_bi.php[tags=!*;mutator_accessor_of_vehicle;maj_inverse_vehicle]
----
<1> mise à jour de l'objet inverse (on associe un technicien au véhicule)

****
//end _show_correction
endif::[]

ifndef::_main_loaded[]
Point suivant :
link:implementation_des_cardinalites.adoc[Implémentation des cardinalités]
include::../config/index.adoc[]
endif::_main_loaded[]

